#!/bin/sh

KERNEL=/dev/virtioblk0.fit0

# use the first partition
global linux.bootargs.rootfs="root=/dev/vda3 rauc.slot=system0 rootwait"

# this boots a FIT image, which contains all required parts at once
bootm -v ${KERNEL}
